---
- name: Manage MySQL Databases
  hosts: DB
  connection: local

  vars: 
    mysql_user: ''
    mysql_password: ''
    mysql_db_name: ''
    mysql_db_encoding: ''

  tasks: 
    - name: Ensure MySQL "{{ mysql_db_name }}" is present
      mysql_db:
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        name: "{{ mysql_db_name }}"
        encoding: "{{ mysql_db_encoding }}"
        state: present
